rm delayedcase_psc.aux
latex delayedcase_psc
bibtex delayedcase_psc
latex delayedcase_psc
pdflatex delayedcase_psc.tex
evince delayedcase_psc.pdf
rm delayedcase_psc.aux
rm delayedcase_psc.bbl
rm delayedcase_psc.blg
rm delayedcase_psc.log
rm delayedcase_psc.dvi
